sudo: required

language: ruby

services:
  - docker

before_install:
  - docker build -t core23/jenkins-php-ci .
  - docker run -d -p 8080:8080 --name jenkins-php-ci core23/jenkins-php-ci

script:
- docker ps | grep -q jenkins-php-ci
