version: '2'

services:
    jenkins:
        build: .
        ports:
            - "50000:50000"
            - "8080:8080"
        environment:
            TIMEZONE: ${TIMEZONE}
        volumes:
            - ${LOCAL_DATA}:/var/jenkins_home
